#task 1 : PR is merged into main folder from another branch completed
#task 2 : commmit message "BUILD_CONTAINER_IMAGE" 
name: Build Container Image  

on:
  push:
    branches:
      - main 
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for PR merged into main
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
        run: |
          echo "PR merged into main! Triggering image build."
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }} ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest

      - name: Check commit message for specific string
        if: contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')
        run: |
          echo "Commit message contains 'BUILD_CONTAINER_IMAGE'. Triggering image build."
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }} ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest
