name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Change this to your main branch name or desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t guestbook-go:${{ github.run_id }} .
          docker tag guestbook-go:${{ github.run_id }} ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }}
          docker tag guestbook-go:${{ github.run_id }} ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest
          
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest

      - name: Removeing Docker Images from local machine
        run: |
          docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:${{ github.run_id }}
          docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go:latest
